### ISSUE TITLE
Cluster Status Shard Allocation Serialization Failure

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/metrics-portal#205]
Linking the shard allocation strategy to the status cache and then accessing the status leads to a serialization failure due to a circular reference. This is probably also a problem in Cluster Aggregator. 

See: https://github.com/ArpNetworking/metrics-portal/pull/203

Error:
```
{
  "time": "2019-05-22T17:25:50.708Z",
  "name": "log",
  "level": "crit",
  "data": {
    "message": "error processing request",
    "request": {
      "_id": "3ec5c152",
      "_class": "play.mvc.Http$RequestImpl"
    }
  },
  "exception": {
    "type": "java.util.concurrent.CompletionException",
    "message": "java.lang.IllegalArgumentException: Direct self-reference leading to cycle (through reference chain: models.view.StatusResponse[\"allocations\"]->java.util.Collections$UnmodifiableRandomAccessList[0]->models.internal.ShardAllocation[\"shardRegion\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.RepointableActorRef[\"parent\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.LocalActorRefProvider$$anon$1[\"parent\"])",
    "backtrace": [
      "at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)",
      "at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)",
      "at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)",
      "at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)",
      "at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)",
      "at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)",
      "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:55)",
      "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:53)",
      "at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)",
      "at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)",
      "at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)",
      "at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)",
      "at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)",
      "at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)",
      "at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"
    ],
    "data": {
      "_id": "4ca18ffe",
      "_class": "java.util.concurrent.CompletionException",
      "cause": {
        "type": "java.lang.IllegalArgumentException",
        "message": "Direct self-reference leading to cycle (through reference chain: models.view.StatusResponse[\"allocations\"]->java.util.Collections$UnmodifiableRandomAccessList[0]->models.internal.ShardAllocation[\"shardRegion\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.RepointableActorRef[\"parent\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.LocalActorRefProvider$$anon$1[\"parent\"])",
        "backtrace": [
          "at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2790)",
          "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
          "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
          "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
          "at java.lang.reflect.Method.invoke(Method.java:498)",
          "at com.arpnetworking.commons.jackson.databind.ImmutableObjectMapper$SafeMethodCallback.intercept(ImmutableObjectMapper.java:172)",
          "at com.fasterxml.jackson.databind.ObjectMapper$$EnhancerByCGLIB$$25450023.valueToTree(<generated>)",
          "at controllers.MetaController.lambda$1(MetaController.java:112)",
          "at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)",
          "at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)",
          "at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)",
          "at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)",
          "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:55)",
          "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:53)",
          "at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)",
          "at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)",
          "at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)",
          "at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)",
          "at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)",
          "at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)",
          "at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"
        ],
        "data": {
          "_id": "9f19df1",
          "_class": "java.lang.IllegalArgumentException",
          "cause": {
            "type": "com.fasterxml.jackson.databind.exc.InvalidDefinitionException",
            "message": "Direct self-reference leading to cycle (through reference chain: models.view.StatusResponse[\"allocations\"]->java.util.Collections$UnmodifiableRandomAccessList[0]->models.internal.ShardAllocation[\"shardRegion\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.RepointableActorRef[\"parent\"]->akka.actor.LocalActorRef[\"parent\"]->akka.actor.LocalActorRefProvider$$anon$1[\"parent\"])",
            "backtrace": [
              "at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)",
              "at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:944)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:721)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)",
              "at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)",
              "at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)",
              "at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:380)",
              "at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)",
              "at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)",
              "at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)",
              "at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)",
              "at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)",
              "at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2643)",
              "at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2785)",
              "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
              "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
              "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
              "at java.lang.reflect.Method.invoke(Method.java:498)",
              "at com.arpnetworking.commons.jackson.databind.ImmutableObjectMapper$SafeMethodCallback.intercept(ImmutableObjectMapper.java:172)",
              "at com.fasterxml.jackson.databind.ObjectMapper$$EnhancerByCGLIB$$25450023.valueToTree(<generated>)",
              "at controllers.MetaController.lambda$1(MetaController.java:112)",
              "at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)",
              "at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)",
              "at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)",
              "at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)",
              "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:55)",
              "at scala.concurrent.java8.FuturesConvertersImpl$CF$$anon$1.accept(FutureConvertersImpl.scala:53)",
              "at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)",
              "at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)",
              "at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)",
              "at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)",
              "at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)",
              "at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)",
              "at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"
            ],
            "data": {
              "_id": "2a9289f7",
              "_class": "com.fasterxml.jackson.databind.exc.InvalidDefinitionException"
            }
          }
        }
      }
    }
  },
  "context": {
    "host": "733c4bf9c04e",
    "processId": "1",
    "threadId": "mportal-akka.actor.default-dispatcher-3",
    "logger": "g.ErrorHandler",
    "line": "50",
    "file": "ErrorHandler.java",
    "class": "global.ErrorHandler"
  },
  "id": "e605e4d6-720c-4228-865e-a95f963d7190",
  "version": "0"
}
```

**Comment by BrandonArp** [comment]
Ahh.... I remember this. I had written a Jackson module for handling Akka references.  See https://github.com/ArpNetworking/metrics-cluster-aggregator/tree/master/src/main/java/com/arpnetworking/configuration/jackson/akka

**Comment by vjkoskela** [comment]
Addressed in: https://github.com/ArpNetworking/metrics-portal/pull/206
